"use client";

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#f8faf8", fontFamily: "Georgia, serif" }}>
      <div style={{ maxWidth: "680px", margin: "0 auto", padding: "48px 24px" }}>
        <a href="/social" style={{ color: "#84a98c", fontSize: "14px", textDecoration: "none", fontFamily: "-apple-system, sans-serif" }}>&larr; Back</a>

        <h1 style={{ fontSize: "28px", fontWeight: "400", color: "#1a2e1a", margin: "32px 0 8px" }}>Terms of Service</h1>
        <p style={{ fontSize: "12px", color: "#84a98c", fontFamily: "-apple-system, sans-serif", marginBottom: "32px" }}>Last updated: March 19, 2026</p>

        <div style={{ fontSize: "14px", color: "#2d4a3e", lineHeight: 1.8, fontFamily: "-apple-system, sans-serif" }}>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>1. Acceptance of Terms</h2>
          <p>By downloading, accessing, or using BeBoldn ("the App"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the App.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>2. Description of Service</h2>
          <p>BeBoldn is a conversation practice application that uses artificial intelligence to help users rehearse social interactions. The App provides simulated conversation scenarios for educational and entertainment purposes only.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>3. Important Disclaimers</h2>
          <p style={{ background: "#fff3f3", padding: "16px", borderRadius: "12px", border: "1px solid #fecaca", marginBottom: "16px" }}>
            <strong style={{ color: "#c0392b" }}>PLEASE READ CAREFULLY:</strong><br/><br/>
            <strong>Not Professional Advice.</strong> BeBoldn is NOT a substitute for professional therapy, counseling, psychology, psychiatry, legal advice, medical advice, or any other professional service. The App does not provide mental health treatment or diagnosis.<br/><br/>
            <strong>No Guarantee of Outcomes.</strong> The developer makes no representations or warranties regarding the effectiveness of the conversation practice, advice, or suggestions provided by the App. Results may vary. The App cannot guarantee any particular outcome in your real-life conversations or relationships.<br/><br/>
            <strong>AI-Generated Content.</strong> All responses in the App are generated by artificial intelligence. AI responses may be inaccurate, inappropriate, incomplete, or unsuitable for your specific situation. You should exercise your own judgment before applying anything from the App to real-life situations.<br/><br/>
            <strong>No Liability for Relationship Outcomes.</strong> The developer is not responsible for any harm, injury, emotional distress, damaged relationships, lost opportunities, misunderstandings, conflicts, or any other negative consequences that may arise from using the App or applying its suggestions to real-life situations.<br/><br/>
            <strong>Use at Your Own Risk.</strong> You acknowledge and agree that your use of the App and any actions you take based on the App's content are entirely at your own risk.
          </p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>4. Limitation of Liability</h2>
          <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE DEVELOPER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, WHETHER ARISING FROM CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE, EVEN IF THE DEVELOPER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
          <p>IN NO EVENT SHALL THE DEVELOPER'S TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID FOR THE APP IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>
          <p>You agree to indemnify and hold harmless the developer from any claims, damages, losses, or expenses arising from your use of the App or your violation of these Terms.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>5. Subscriptions and Payments</h2>
          <p>BeBoldn offers a free tier with limited sessions and a paid subscription ("BeBoldn Pro") for unlimited access.</p>
          <p><strong>Billing.</strong> Subscriptions are billed monthly through Apple's App Store. Payment is charged to your Apple ID account at confirmation of purchase.</p>
          <p><strong>Auto-Renewal.</strong> Your subscription automatically renews unless canceled at least 24 hours before the end of the current billing period. Your account will be charged for renewal within 24 hours prior to the end of the current period.</p>
          <p><strong>Cancellation.</strong> You may cancel your subscription at any time through your Apple ID account settings. Cancellation takes effect at the end of the current billing period. No refunds are provided for partial billing periods.</p>
          <p><strong>Price Changes.</strong> Prices may change. You will be notified in advance and given the opportunity to cancel before any price increase takes effect.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>6. User Conduct</h2>
          <p>You agree not to use the App to:</p>
          <p style={{ paddingLeft: "16px" }}>
            - Harass, threaten, or harm others<br/>
            - Generate content that is illegal, abusive, or hateful<br/>
            - Attempt to manipulate or exploit the AI system<br/>
            - Violate any applicable laws or regulations<br/>
            - Use the App for any purpose other than personal conversation practice
          </p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>7. Intellectual Property</h2>
          <p>All content, features, and functionality of the App are owned by the developer and are protected by copyright, trademark, and other intellectual property laws. You may not reproduce, distribute, or create derivative works from any part of the App.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>8. Privacy</h2>
          <p>Your use of the App is also governed by our <a href="/privacy" style={{ color: "#2d6a4f" }}>Privacy Policy</a>. By using the App, you consent to the collection and use of information as described in the Privacy Policy.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>9. Age Requirement</h2>
          <p>You must be at least 13 years of age to use the App. If you are under 18, you must have the consent of a parent or legal guardian. The App is not intended for children under 13.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>10. Disclaimer of Warranties</h2>
          <p>THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. THE DEVELOPER DOES NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>11. Modifications</h2>
          <p>The developer reserves the right to modify these Terms at any time. Continued use of the App after changes constitutes acceptance of the new Terms. Material changes will be communicated through the App.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>12. Governing Law</h2>
          <p>These Terms shall be governed by and construed in accordance with the laws of the State of New York, United States, without regard to conflict of law provisions.</p>

          <h2 style={{ fontSize: "18px", fontWeight: "600", color: "#1a2e1a", margin: "28px 0 12px", fontFamily: "Georgia, serif" }}>13. Contact</h2>
          <p>If you have questions about these Terms, contact us at: <a href="/support" style={{ color: "#2d6a4f" }}>BeBoldn Support</a></p>

          <div style={{ marginTop: "48px", padding: "20px", background: "#f0f7f2", borderRadius: "12px", fontSize: "13px", color: "#52796f" }}>
            <strong>Summary:</strong> BeBoldn is a conversation practice tool for educational and entertainment purposes. It is not therapy or professional advice. The developer is not responsible for any outcomes from applying the App's suggestions to real life. Use the App at your own risk. Subscriptions auto-renew and can be canceled anytime through your Apple ID settings.
          </div>
        </div>
      </div>
    </div>
  );
}
